// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1pMh1l2qlNVQ0fW3wXI3EtLvf4giGEiE',
    appId: '1:1044554595821:web:353ff12975ded9cd757be4',
    messagingSenderId: '1044554595821',
    projectId: 'rajivn-enterprises-28234',
    authDomain: 'rajivn-enterprises-28234.firebaseapp.com',
    storageBucket: 'rajivn-enterprises-28234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJLEw6U8umISHerqkNV4OiZinWIqZw6s',
    appId: '1:1044554595821:android:f2e8c07740b95eea757be4',
    messagingSenderId: '1044554595821',
    projectId: 'rajivn-enterprises-28234',
    storageBucket: 'rajivn-enterprises-28234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGzA0UId7NxkTUALcEqb07AKsIoAOjEjQ',
    appId: '1:1044554595821:ios:ca75172fe70a5cc1757be4',
    messagingSenderId: '1044554595821',
    projectId: 'rajivn-enterprises-28234',
    storageBucket: 'rajivn-enterprises-28234.appspot.com',
    iosBundleId: 'com.example.rajivnEnterprises',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGzA0UId7NxkTUALcEqb07AKsIoAOjEjQ',
    appId: '1:1044554595821:ios:ca75172fe70a5cc1757be4',
    messagingSenderId: '1044554595821',
    projectId: 'rajivn-enterprises-28234',
    storageBucket: 'rajivn-enterprises-28234.appspot.com',
    iosBundleId: 'com.example.rajivnEnterprises',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1pMh1l2qlNVQ0fW3wXI3EtLvf4giGEiE',
    appId: '1:1044554595821:web:0e9d51d0c2791545757be4',
    messagingSenderId: '1044554595821',
    projectId: 'rajivn-enterprises-28234',
    authDomain: 'rajivn-enterprises-28234.firebaseapp.com',
    storageBucket: 'rajivn-enterprises-28234.appspot.com',
  );
}
